<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-D5BDHV5" failures="0" tests="6" name="TestCases.InvalidTestCases" time="74.768" errors="1" timestamp="2020-06-15T11:00:53 IST" skipped="0">
  <testcase classname="TestCases.InvalidTestCases" name="get_Test_Case_Result" time="0.597">
    <error message="The supplied file was empty (zero bytes long)" type="org.apache.poi.EmptyFileException">
      <![CDATA[org.apache.poi.EmptyFileException: The supplied file was empty (zero bytes long)
at org.apache.poi.util.IOUtils.peekFirstNBytes(IOUtils.java:111)
at org.apache.poi.poifs.filesystem.FileMagic.valueOf(FileMagic.java:206)
at org.apache.poi.openxml4j.opc.internal.ZipHelper.verifyZipHeader(ZipHelper.java:143)
at org.apache.poi.openxml4j.opc.internal.ZipHelper.openZipStream(ZipHelper.java:175)
at org.apache.poi.openxml4j.opc.ZipPackage.<init>(ZipPackage.java:104)
at org.apache.poi.openxml4j.opc.OPCPackage.open(OPCPackage.java:307)
at org.apache.poi.ooxml.util.PackageHelper.open(PackageHelper.java:47)
at org.apache.poi.xssf.usermodel.XSSFWorkbook.<init>(XSSFWorkbook.java:309)
at Setup.ExportToExcel.write_Into_Excel(ExportToExcel.java:22)
at TestCases.InvalidTestCases.get_Test_Case_Result(InvalidTestCases.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:63)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:348)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:302)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:695)
at org.testng.internal.TestInvoker.runAfterGroupsConfigurations(TestInvoker.java:671)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:655)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </error>
  </testcase> <!-- get_Test_Case_Result -->
  <system-out/>
  <testcase classname="TestCases.InvalidTestCases" name="test_Same_Location_Of_Journey" time="16.033"/>
  <system-out/>
  <testcase classname="TestCases.InvalidTestCases" name="test_Invalid_Date_Of_Journey" time="2.419"/>
  <system-out/>
  <testcase classname="TestCases.InvalidTestCases" name="test_ReturnDate_Disabled" time="1.025"/>
  <system-out/>
  <testcase classname="TestCases.InvalidTestCases" name="test_OutstationTrip_Selected" time="1.630"/>
  <system-out/>
  <testcase classname="TestCases.InvalidTestCases" name="test_GiftCard" time="53.064"/>
  <system-out/>
</testsuite> <!-- TestCases.InvalidTestCases -->
